---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: 'db01'
    - dbname: 'notes'
    - dbusername: 'notesapp'
    - dbpassword: 'devopsmaonamassa'
  tasks:
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500
    - name: Donwload do maven #Utilizo esta versão pois é compactivel com o spring que estamos utilizando de exemplo no projeto
      get_url:
        #url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/apache-maven-3.8.6-bin.tar.gz
    - name: Unzip do pacote maven
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Instalação do Java
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest
    - name: Criação do diretório de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: instalacao do git client
      yum:
        name: git
        state: latest
    - name: Clone do repositório Notes - app
      git:
        repo: 'https://github.com/luissimon96/spring-boot-mysql-rest-api-tutorial.git' #apontar para seu repositório caso seja realizado um Fork para seu GitHub
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacote da aplicação
      command: sudo /opt/apache-maven-3.8.6/bin/mvn -Dskipytest -f /opt/notes/pom.xml package
      become_user: app
    - name: Registrar versao atual do pacote
      shell:
        cmd: sudo /opt/apache-maven-3.8.6/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version
    - name: Configurar serviço do Systemd
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
        owner: root
        group: root
        mode: '0600'
      notify: reload daemon
    - name: Iniciar serviço notes
      service:
        name: notes
        state: restarted
  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes
