Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs" Utilizado para criar no Linux as duas linhas abaixo sáo para o Windows
  config.vm.synced_folder ".", "/vagrant", type: "rsync",
  rsync__exclude: ".git/"
  config.vm.provision "shell", path: "provision.sh"
end