mysql_root_password: devopsmaonamassa
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: '%'
    passowrd: devopsmaonamassa
    priv: 'notes.*:ALL'
