Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.1.3"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs" Utilizado para criar no Linux as duas linhas abaixo sáo para o Windows
  #config.vm.synced_folder ".", "/vagrant", type: "rsync",
  #rsync__exclude: ".git/" Não é necessário a montagem pois só é necessário montar no Control-Node.
  #config.vm.provision "shell", path: "provision.sh" Também não é necessário.
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end