Vagrant.configure("2") do |config|
  config.vm.box = "danielbueno99/xampp"
  config.vm.box_version = "1.0.0"
  config.vm.hostname = "xampp"
  config.vm.network "private_network", ip: "192.168.1.5"
  config.vm.network "forwarded_port", guest: 3310, host: 3310
  config.vm.provision "shell", path: "provision.sh"
end